//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVAOWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int Id { get; set; }
        public string PageName { get; set; }
        public string Description { get; set; }
        public string UrlPath { get; set; }
        public Nullable<int> ParentMenu { get; set; }
        public string Icon { get; set; }
        public int Order { get; set; }
        public bool IsParent { get; set; }
        public bool Visible { get; set; }
        public bool AccessibleByAll { get; set; }
        public bool Active { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
