//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVAOWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordHistory
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public string Password { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
